sudo: false
language: java
install: ./gradlew wpi
script: ./gradlew clean jar -PciBuild=true
jdk: oraclejdk8
deploy:
  - provider: releases
    api_key:
      secure: R1YsQIVy+SdDBbJpwLrAdnh5w8Xp4UT2ExsrCLOHbfv1NAq/vPrt8/iIs8o2nj6Z7KY7ZZyDrGoREVVG5WKWCd0rVSMXRD8v+JHSxSRhdYnpc6VyOEB4A2LbQQi4bEal+YzJPTDsyP2fNPQH8srDozcfiJumaF9O/ob8MczSVx/EZCqFgY3Mmk8dMPzguiCU92ibYiajgpDETjRyT+3hsRYsFM4DNMoXPI/1NZJJtZSpyMJQLuz0s54u3GBxjv+d4luTq7S/hyKmsgV7YU3/RSWUnIqCvPqJA301XwLtT2Xm/rPPaI/rybvtiZTczaE9Kmhzop2mW6nFZGVPRnDK8ZuYkE3EM4FYYK7PCGtfeXiOL1UGZiVeoLNWEfMN6VctrIhZjnyqLSLJes0H0lfVdrQiIgS1vSfTsk39lm2JD1Cu9mCgpoXzkuoWCxgPFC8Ys9hShRCOFm7VLzh+aznUxAtHtOtA5CCwgejoP1hIPE+dfYwE69aKL+MXkALAcnNqjqM2nlVu4nB9cSIQ+oimAQntdb80DncXihNsurwoAhmPe2IC+k3n3S52ijWzxpSCmiud7oVPCbqCkTEIJkYED+mg1AZqPlkv+5rjDRxEo25UOWD3EhvNT+WQjbeasmEwBQweyjdBoUSCDCRuCTULdrN5I0izgZ/XFDEHc9ZOuuY=
    file: build/libs/CiDemo.jar
    on:
      tags: true
  - provider: bintray
    file: bintraydescriptor.json
    user: johnrudolflewis
    key: 
      secure: "kGEaVV6h8tQLVM+w+uMPN2aQiXaw/9onmIUNO7iZFu554DczdpbDf8gPz5AlABwc5XiF3yUy1c9v5NjA5HOjhhe8KAwR1274KSbA3PRXfLgTvHF/lEV77orKzKbTHIkKL80IOuqWuR10d2W2moMMq/O5vf+8KyOgEo6sy6ZtHmZwheO2mD2UCfYqsNAfhjLPkVpYZW0aOx/YhvQs3ejIN+l99g7Kd3u+ld7q74g74sXYzJCL4tG+gd5eja5N2Wow2SYA+mB1mHQLrExgPZmKVZKnGEU2OjFY7e9aFJESKizJlft+M9endSoXgN3Qoo+frhe4SpAF/ccjXvaJfINoSI4KGDoCFcPhuRDxTAmrJ4+C8eTd9aDiTmhn1lCbJ3dPrPyt8M+GGaXE7aEQaaXCxrYX4f7KYueG/0fSb2esMwmd5LZ8XBWWGi7PZKO4fgbgu0evyYTGY7a9yYu1FDEX5RlntPRJec5BKYpsDHDxbYPvNvlunq+t5qdWihzsrv8nCklb2esFnhXtIeuCLONBpv5OZM/dsry08yPNOMzV79Q1BnjDCf18DDGu8wqBAbIQMKLJ6kgbo7N/3J07ubiIfRx6lgSW697ugsqnw1LT7W/hZ1GUZqEovIsNjrIBbzUYJhOHXQtxTKY8P/EcuZEdAGQmbTywY49HjIBdM6fgkYc="
